### ISSUE TITLE
Cannot set properties

### ISSUE THREAD

**Issue by Lugoto** [bigarmTomi/spotify-now-playing#2]
![Screenshot_1](https://user-images.githubusercontent.com/8899625/199509940-8aac0e4b-3bbb-4809-888f-de990d163930.png)

Hello, I have an error in the api call. All my keys are good.
Thank you in advance for your answer.

**Comment by Lugoto** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/8899625/199511333-abd22d77-16f1-476c-8db6-288ea51b982a.png)

**Comment by Lugoto** [comment]
Hello,
Thanks a lot for your help. I now have access to API errors.
I now have a credentials error even though I updated my refresh token.
Do you have any idea where it could come from?
Thank you, have a nice day!

![Screenshot_3](https://user-images.githubusercontent.com/8899625/199721755-6ca0739b-9a3a-40ce-916a-8ded8f012ebb.png)

**Comment by bigarmTomi** [comment]
Hi!
Theoretically, this error should only occur if you entered invalid credentials as parameters.
Try debugging the code and make sure that the given data are not undefined.

If the problem persists, try creating a new application in the [Spotify Dashboard](https://developer.spotify.com/dashboard/) and follow the instructions in the [README](https://github.com/bigarmTomi/spotify-now-playing#-usage) file.

Have a nice day!
